[package]
name = "rust-nes"
version = "0.1.0"
authors = ["Junichiro Kasuya <junichiro.kasuya@gmail.com>"]

[dependencies]
sdl2 = "0.30"
bytes = "0.4"
timer = "0.2.0"
chrono = "0.4.0"
bmp = "*"
log = "0.3"
env_logger = "*"
bitflags = "*"
